easy_admin:
    design:
        assets:
            js:
                - 'bundles/tinymce/tinymce.min.js'
                - 'tinymce/tinymce.init.js'
    site_name: 'Sf4 sandbox'
    formats:
        date:     'd/m/Y'
        time:     'H:i'
        datetime: 'd/m/Y h:i A'
        number:   '%.2f'
    entities:
        Blog:
            class: App\Entity\Blog
            label: 'Blog entries'
            list:
                title: '%%entity_label%%'
                fields:
                    - 'createdAt'
                    - 'title'
                    - 'shortContent'
                    - 'author'
            form:
                fields:
                    - 'title'
                    - 'shortContent'
                    - 'content'
        # Page:
        #     class: App\Entity\Page
        #     label: 'Custom pages'
        #     list:
        #         title: '%%entity_label%%'
        #         fields:
        #             - 'name'
        #             - 'parent'
        #             - 'is_active'
        #     form:
        #         fields:
        #             - 'title'
        #             - { property: 'parent', type: 'easyadmin_autocomplete', type_options: { class: 'App\Entity\Page' } }
        #             - 'name'
        #             - 'body'
        #             - 'is_active'
        # User:
        #     class: App\Entity\User
        #     label: 'Users'
        #     list:
        #         title: '%%entity_label%%'
        #         fields:
        #             - 'username'
        #             - 'email'
        #             - 'is_active'
